/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.GuiController;
import model.Utente;
import java.util.Timer;
import javafx.scene.Parent;
import javax.swing.JFrame;
import message.TimeMessage;

/**
 *
 * @author Giuseppe
 */
public class ChooseFrame extends javax.swing.JFrame {

    public Utente user;
    private LoginForm Parent;


    /**
     * 
     * @param user
     * @param Parent 
     */
    public ChooseFrame(Utente user, LoginForm Parent) {
        this.user=user;
        this.Parent = Parent;
        initComponents();
        LabelSaluto.setText("Benvenuto "+user.Username);
        TimeMessage trd1 = new TimeMessage(user, StatusMessage);
        Timer orologio = new Timer();
        orologio.schedule(trd1, 0, 10000);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studiosLabel = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        SendMessage = new javax.swing.JToggleButton();
        ReadMessage = new javax.swing.JButton();
        DecriptMessage = new javax.swing.JButton();
        Status = new javax.swing.JLabel();
        StatusMessage = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        LabelSaluto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studiosLabel.setText("Batracomiomachia Studios");

        Title.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Title.setText("Progetto di Sviluppo");

        SendMessage.setText("Manda Messaggio");
        SendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendMessageActionPerformed(evt);
            }
        });

        ReadMessage.setText("Leggi Messaggio");
        ReadMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadMessageActionPerformed(evt);
            }
        });

        DecriptMessage.setText("Decifrare Messaggio");
        DecriptMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecriptMessageActionPerformed(evt);
            }
        });

        Status.setText(".");

        StatusMessage.setText("Ci sono 0 messaggi per te!");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        LabelSaluto.setText("Benvenuto NOME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelSaluto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReadMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DecriptMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StatusMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studiosLabel)
                    .addComponent(Title))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studiosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(SendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReadMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DecriptMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout)
                    .addComponent(LabelSaluto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendMessageActionPerformed
        // TODO add your handling code here:
        GuiController.NewMessage(user, this);
        
        
    }//GEN-LAST:event_SendMessageActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        GuiController.Logout(Parent, this);
        Status.setText(GuiController.NotImplementYet());
    }//GEN-LAST:event_logoutActionPerformed

    private void ReadMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadMessageActionPerformed
        // TODO add your handling code here:
        GuiController.GoReadMessage(user, this);
    }//GEN-LAST:event_ReadMessageActionPerformed

    private void DecriptMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecriptMessageActionPerformed
        // TODO add your handling code here:
        GuiController.GoDecriptSession(user, this);
    }//GEN-LAST:event_DecriptMessageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DecriptMessage;
    private javax.swing.JLabel LabelSaluto;
    private javax.swing.JButton ReadMessage;
    private javax.swing.JToggleButton SendMessage;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel StatusMessage;
    private javax.swing.JLabel Title;
    private javax.swing.JButton logout;
    private javax.swing.JLabel studiosLabel;
    // End of variables declaration//GEN-END:variables

    public void sendMessage(String text)
    {
        Status.setText(text);
    }
}
